### ISSUE TITLE
Problema na instalação

### ISSUE THREAD

**Issue by Wendell00** [MichaelDeMattos/dollar-to-brl#7]
Após usar o comando no terminal a pasta é movida para o .local/share/gnome-shell/extensions/ porém não aparece na extensions, por que?

![image](https://github.com/MichaelDeMattos/dollar-to-brl/assets/62032363/62ad1ab5-67c1-4eef-aeed-5c73b2c2a13e)
![image](https://github.com/MichaelDeMattos/dollar-to-brl/assets/62032363/b25ab55a-9d6a-43eb-bff1-b920489c25bf)

**Comment by MichaelDeMattos** [comment]
Obrigado por relatar este problema, estou subindo a correção dos comandos para instalação.

**Comment by MichaelDeMattos** [comment]
Favor utilizar o novo comando disponibilizado na branch main.

cd /tmp && git clone https://github.com/MichaelDeMattos/dollar-to-brl.git && cp -av dollar-to-brl ~/.local/share/gnome-shell/extensions/ && gnome-shell-extension-tool --enable-extension dollar-to-brl
